# Generated by Django 5.2.15 on 2026-06-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='houser_photo',
        ),
        migrations.AddField(
            model_name='house',
            name='houser_photo1',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AddField(
            model_name='house',
            name='houser_photo2',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AddField(
            model_name='house',
            name='houser_photo3',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AddField(
            model_name='house',
            name='houser_photo4',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AddField(
            model_name='house',
            name='houser_photo5',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография домика'),
        ),
    ]
