# Generated by Django 5.2.15 on 2026-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_house_houser_photo1_alter_house_houser_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='houser_photo1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houser_photo2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houser_photo3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houser_photo4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media', verbose_name='Фотография домика'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houser_photo5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media', verbose_name='Фотография домика'),
        ),
    ]
