# Generated by Django 5.2.15 on 2026-06-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_house_houser_photo1_alter_house_houser_photo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='houser_photo1',
            new_name='house_photo1',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='houser_photo2',
            new_name='house_photo2',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='houser_photo3',
            new_name='house_photo3',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='houser_photo4',
            new_name='house_photo4',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='houser_photo5',
            new_name='house_photo5',
        ),
    ]
