# Generated by Django 5.2.15 on 2026-07-01 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_houser_photo1_house_house_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.TextField(default='Домик', verbose_name='Название домика')),
                ('house_photo', models.ImageField(upload_to='media', verbose_name='Фотография домика')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотки',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo4',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo5',
        ),
        migrations.AddField(
            model_name='house_photo',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.house'),
        ),
    ]
