# Generated by Django 5.2.15 on 2026-07-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_house_photo_delete_payment_remove_house_house_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_photo',
            name='house',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='House_photo',
        ),
    ]
