# Generated by Django 5.2.15 on 2026-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
            ],
            options={
                'verbose_name': 'Access token',
            },
        ),
        migrations.CreateModel(
            name='Refresh_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
            ],
            options={
                'verbose_name': 'Refresh token',
            },
        ),
    ]
