# Generated by Django 5.2.15 on 2026-07-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_access_token_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_token',
            name='access_token',
            field=models.TextField(verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='refresh_token',
            name='refresh_token',
            field=models.TextField(verbose_name='Refresh Token'),
        ),
    ]
